### ISSUE TITLE
Support CMD-based hotkeys

### ISSUE THREAD

**Issue by danybony** [frakbot/chrome-github-editor#2]
Because on Mac OS it's a pain to use `CMD+something` everywhere and `CTRL+something` here

**Comment by rock3r** [comment]
I suppose @frapontillo's reply will be something along the lines of "PR or GTFO" lol

**Comment by rock3r** [comment]
Also totally already lol-ing at the moment someone tries doing a [blockquote](https://github.com/frakbot/chrome-github-editor/blob/master/app/scripts/contentscript.js#L44) on Mac OS...

**Comment by danybony** [comment]
Naa, @frapontillo is a Sir, I'm sure he will be happy to work on this again XD

> I suppose @frapontillo's reply will be something along the lines of "PR or GTFO" lol

**Comment by frapontillo** [comment]
I ain't no sir, yo.
PR or GTFO

**Comment by frapontillo** [comment]
@danybony try out the latest `feature/mac-support` branch, please. I don't have any spare Macs around as of now.

**Comment by danybony** [comment]
@frapontillo confirmed working on Yosemite
![](http://i.giphy.com/vMNoKKznOrUJi.gif)

**Comment by frapontillo** [comment]
Released in `0.0.5`.
