### ISSUE TITLE
Ctrl+L for links, Ctrl+K for code

### ISSUE THREAD

**Issue by borekb** [frakbot/chrome-github-editor#3]
Very nice extension, it would just be nice if it used the de-facto standard shortcuts for links (Ctrl+L) and code (Ctrl+K) which is used by StackOverflow, Discourse, StackEdit, overv.io and many others.

**Comment by rock3r** [comment]
@borekb ctrl/cmd-k for links is the de facto standard for the vast majority of web sites and apps... Google's, Microsoft's, Apple's and many others' software uses ctrl/cmd-l to left-align and k for links. So I'd say nay, leave it as it is.

**Comment by borekb** [comment]
You're generally right but for some reason, Markdown editors almost universally settled on Ctrl + `L`. Just talking from experience, it is painful for myself to constantly mind-switch between `K` and `L` as I use both Word, OneNote, WordPress, Gmail, Google Docs (all `K`) as well as StackOverflow, StackEdit, Discourse, overv.io and MarkdownPad (all `L`).

**Comment by frapontillo** [comment]
I'd stay with K as well, changing it now would indeed make us mind-switching.

**Comment by borekb** [comment]
Any chance to make it configurable?

**Comment by frapontillo** [comment]
I would gladly accept a PR, but it would have to include a framework for setting generic key mapping options.

**Comment by borekb** [comment]
I thought you might say this :) I personally would be happy enough with some hacky way to do this it's ultimately your call.
